# Generated by Django 5.1.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # Add indexes for User model
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='app_user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant_id'], name='app_user_tenant_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'tenant_id'], name='app_user_active_tenant_idx'),
        ),
        
        # Add indexes for Role model
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name', 'tenant_id'], name='app_role_name_tenant_idx'),
        ),
        
        # Add indexes for Permission model  
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['name'], name='app_permission_name_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['resource', 'action'], name='app_permission_resource_action_idx'),
        ),
        
        # Add indexes for AuditLog model
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'action', 'created_at'], name='app_audit_user_action_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource', 'created_at'], name='app_audit_resource_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['tenant_id', 'created_at'], name='app_audit_tenant_time_idx'),
        ),
        
        # Add indexes for Transaction model if it exists
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS app_transaction_date_idx ON app_transaction(date DESC);",
            reverse_sql="DROP INDEX IF EXISTS app_transaction_date_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS app_transaction_category_date_idx ON app_transaction(category, date DESC);",
            reverse_sql="DROP INDEX IF EXISTS app_transaction_category_date_idx;"
        ),
    ]