# Generated by Team Gamma (Database & Performance Agents) on 2025-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_indexes'),
    ]

    operations = [
        # Add additional performance indexes
        migrations.RunSQL(
            """
            -- Composite indexes for multi-tenant queries
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_account_user_type 
            ON app_account(created_by_id, account_type);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transaction_account_date 
            ON app_transaction(account_id, date DESC);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transaction_category_date 
            ON app_transaction(category, date DESC);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_budget_user_dates 
            ON app_budget(created_by_id, start_date, end_date);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_auditlog_user_timestamp 
            ON app_auditlog(user_id, timestamp DESC);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_auditlog_resource_timestamp 
            ON app_auditlog(resource_type, resource_id, timestamp DESC);
            
            -- Partial indexes for active records
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_active_email 
            ON app_user(email) WHERE is_active = true;
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transaction_recent 
            ON app_transaction(account_id, date DESC, amount) 
            WHERE date >= CURRENT_DATE - INTERVAL '1 year';
            """,
            reverse_sql="""
            DROP INDEX CONCURRENTLY IF EXISTS idx_account_user_type;
            DROP INDEX CONCURRENTLY IF EXISTS idx_transaction_account_date;
            DROP INDEX CONCURRENTLY IF EXISTS idx_transaction_category_date;
            DROP INDEX CONCURRENTLY IF EXISTS idx_budget_user_dates;
            DROP INDEX CONCURRENTLY IF EXISTS idx_auditlog_user_timestamp;
            DROP INDEX CONCURRENTLY IF EXISTS idx_auditlog_resource_timestamp;
            DROP INDEX CONCURRENTLY IF EXISTS idx_user_active_email;
            DROP INDEX CONCURRENTLY IF EXISTS idx_transaction_recent;
            """
        ),
        
        # Add database constraints for data integrity
        migrations.RunSQL(
            """
            -- Add check constraints for data validation
            ALTER TABLE app_account 
            ADD CONSTRAINT chk_account_type 
            CHECK (account_type IN ('checking', 'savings', 'credit', 'investment', 'loan'));
            
            ALTER TABLE app_transaction 
            ADD CONSTRAINT chk_transaction_amount_not_zero 
            CHECK (amount != 0);
            
            ALTER TABLE app_budget 
            ADD CONSTRAINT chk_budget_amount_positive 
            CHECK (amount > 0);
            
            ALTER TABLE app_budget 
            ADD CONSTRAINT chk_budget_date_range 
            CHECK (end_date > start_date);
            
            -- Add currency constraints
            ALTER TABLE app_account 
            ADD CONSTRAINT chk_account_currency 
            CHECK (currency IN ('USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'));
            
            ALTER TABLE app_transaction 
            ADD CONSTRAINT chk_transaction_currency 
            CHECK (currency IN ('USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY'));
            """,
            reverse_sql="""
            ALTER TABLE app_account DROP CONSTRAINT IF EXISTS chk_account_type;
            ALTER TABLE app_transaction DROP CONSTRAINT IF EXISTS chk_transaction_amount_not_zero;
            ALTER TABLE app_budget DROP CONSTRAINT IF EXISTS chk_budget_amount_positive;
            ALTER TABLE app_budget DROP CONSTRAINT IF EXISTS chk_budget_date_range;
            ALTER TABLE app_account DROP CONSTRAINT IF EXISTS chk_account_currency;
            ALTER TABLE app_transaction DROP CONSTRAINT IF EXISTS chk_transaction_currency;
            """
        ),
        
        # Optimize database settings
        migrations.RunSQL(
            """
            -- Update database statistics for better query planning
            ANALYZE;
            
            -- Set optimal database parameters (if permissions allow)
            -- These would typically be set at the database level
            """,
            reverse_sql="-- No reverse SQL needed for ANALYZE"
        ),
    ]