# Generated by Team Sigma (Data Processing & Import) - Sprint 7

import uuid
import django.core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_optimize_database_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='imports/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx', 'xls', 'pdf'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='UPLOADED', max_length=10)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('security_scan_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('CSV', 'CSV File'), ('EXCEL', 'Excel File'), ('PDF', 'PDF File')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_rows', models.IntegerField(blank=True, null=True)),
                ('processed_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('column_mappings', models.JSONField(blank=True, default=dict)),
                ('import_settings', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('keywords', models.JSONField(default=list)),
                ('ml_confidence_threshold', models.FloatField(default=0.8)),
                ('is_system_category', models.BooleanField(default=False)),
                ('is_income_category', models.BooleanField(default=False)),
                ('is_expense_category', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transactioncategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file_type', models.CharField(choices=[('CSV', 'CSV File'), ('EXCEL', 'Excel File'), ('PDF', 'PDF File')], max_length=10)),
                ('column_mappings', models.JSONField()),
                ('data_transformations', models.JSONField(default=dict)),
                ('validation_rules', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('CATEGORIZATION', 'Transaction Categorization'), ('PATTERN_ANALYSIS', 'Pattern Analysis'), ('ANOMALY_DETECTION', 'Anomaly Detection')], max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('training_data_size', models.IntegerField(default=0)),
                ('features_used', models.JSONField(default=list)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('model_file_path', models.CharField(blank=True, max_length=500)),
                ('model_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_production_ready', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('performance_metrics', models.JSONField(default=dict)),
                ('last_training_date', models.DateTimeField(blank=True, null=True)),
                ('last_evaluation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], default='PENDING', max_length=10)),
                ('raw_data', models.JSONField()),
                ('duplicate_confidence', models.FloatField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('has_warnings', models.BooleanField(default=False)),
                ('ml_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.transactioncategory')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_duplicates', to='app.transaction')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='app.importjob')),
                ('ml_predicted_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_predictions', to='app.transactioncategory')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ImportValidationError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('column_name', models.CharField(blank=True, max_length=100)),
                ('field_name', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10)),
                ('error_code', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('suggested_fix', models.TextField(blank=True)),
                ('raw_value', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_action', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='app.importjob')),
            ],
            options={
                'ordering': ['row_number', 'severity'],
            },
        ),
        # Add foreign key relationship
        migrations.AddField(
            model_name='fileupload',
            name='import_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_upload', to='app.importjob'),
        ),
        # Add indexes for performance
        migrations.RunSQL(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fileupload_user_status 
            ON app_fileupload(user_id, status);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_importjob_user_status 
            ON app_importjob(user_id, status);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_importjob_user_created 
            ON app_importjob(user_id, created_at);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_importedtransaction_job_status 
            ON app_importedtransaction(import_job_id, status);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_importedtransaction_job_row 
            ON app_importedtransaction(import_job_id, row_number);
            
            CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_transactioncategory_user_system 
            ON app_transactioncategory(user_id, is_system_category);
            """,
            reverse_sql="""
            DROP INDEX CONCURRENTLY IF EXISTS idx_fileupload_user_status;
            DROP INDEX CONCURRENTLY IF EXISTS idx_importjob_user_status;
            DROP INDEX CONCURRENTLY IF EXISTS idx_importjob_user_created;
            DROP INDEX CONCURRENTLY IF EXISTS idx_importedtransaction_job_status;
            DROP INDEX CONCURRENTLY IF EXISTS idx_importedtransaction_job_row;
            DROP INDEX CONCURRENTLY IF EXISTS idx_transactioncategory_user_system;
            """
        ),
        # Add unique constraints
        migrations.AddConstraint(
            model_name='importtemplate',
            constraint=models.UniqueConstraint(fields=['user', 'name'], name='unique_template_per_user'),
        ),
        migrations.AddConstraint(
            model_name='transactioncategory',
            constraint=models.UniqueConstraint(fields=['user', 'name'], name='unique_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='mlmodel',
            constraint=models.UniqueConstraint(fields=['name', 'version'], name='unique_model_version'),
        ),
    ]